name: Publish
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.36.0"
      - name: Install
        run: deno cache depts.
      - name: Compile
        run: deno task compile-all
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: bin/*
          overwrite: true
          file_glob: true
