name: Publish
on:
  push:
    tags:
      - "*"

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: "1.36.0"
      - name: Install
        run: deno cache deps.ts
      - name: Compile
        run: deno task compile-all
      - name: Upload Linux binaries
        uses: svenstaro/upload-release-action@v2
        with:
          file: bin/sm-linux
          asset_name: sm-linux-$tag
          overwrite: true
      - name: Upload Windows binaries
        uses: svenstaro/upload-release-action@v2
        with:
          file: bin/sm.exe
          asset_name: sm-$tag.exe
          overwrite: true
      - name: Upload Mac (x86_64) binaries
        uses: svenstaro/upload-release-action@v2
        with:
          file: bin/sm-mac
          asset_name: sm-mac-$tag
          overwrite: true

      - name: Upload mac (arm) binaries
        uses: svenstaro/upload-release-action@v2
        with:
          file: bin/sm-mac-arm
          asset_name: sm-mac-arm-$tag
          overwrite: true
